### ISSUE TITLE
Comments for Meteor post

### ISSUE THREAD

**Issue by SirIle** [SirIle/sirile.github.io#3]
Placeholder for the comments.

**Comment by xzhu70** [comment]
It looks there is some file permission issue when running from a directory created by 'git clone https://github.com/SirIle/meteortest.git'.  

  951  cp -r meteortest/ meteortest2
  952  cd meteortest2
  953  ls
  954  meteor

Then it works fine.


Xiangs-MacBook-Pro:meteortest xiangzhu$ meteor
[[[[[ ~/proj/meteor/try/orig/meteortest ]]]]] 

=> Started proxy.                             
                                              
/Users/xiangzhu/.meteor/packages/meteor-tool/.1.1.9.2jr6j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: EACCES, mkdir '/Users/xiangzhu/proj/meteor/try/orig/meteortest/.meteor/local'
    at Object.Future.wait (/Users/xiangzhu/.meteor/packages/meteor-tool/.1.1.9.2jr6j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as mkdir] (/tools/fs/files.js:1334:20)
    at Object.files.mkdir_p (/tools/fs/files.js:405:11)
    at Object.files.mkdir_p (/tools/fs/files.js:395:23)
    at launchOneMongoAndWaitForReadyForInitiate (/tools/runners/run-mongo.js:394:11)
    at launchMongo (/tools/runners/run-mongo.js:656:7)
    at [object Object]._.extend._startOrRestart (/tools/runners/run-mongo.js:756:19)
    at [object Object]._.extend.start (/tools/runners/run-mongo.js:714:10)
    at /tools/runners/run-all.js:168:26
    - - - - -

**Comment by SirIle** [comment]
@xzhu70 Interesting, I wasn't able to reproduce on Mac. Were you on Linux?

**Comment by xzhu70** [comment]
Because you are using the same username so there is no file system
permission problem.

I am on MacPro.

**Comment by SirIle** [comment]
Ahh, okay, wasn't even aware that Git stores anything beyond the file attributes. Would chownin recursively after cloning work? If it does, I'll update the description.

**Comment by scheung38** [comment]
It was working before the conversion to Coffeescript, Jade and Stylus, but after the conversion I just got a blank screen?
